## 错误处理收集

- try catch

> 用于运行时非异步错误，无法处理语法错误和异步错误

```
//运行时非异步错误
try {
    a // 未定义变量 
} catch(e) {
    console.log(e)
}
```
```
//语法错误,无法捕获
try {
    var a =\ 'a'
} catch(e) {
    console.log(e);
}
```

- window.onerror  

> 需要将 window.onerror 放在所有脚本之前，这样才能对语法异常和运行异常进行处理。除了对语法错误和网络错误（因为网络请求异常不会事件冒泡）无能为力以外，无论是异步还是非异步，onerror 都能捕获到运行时错误。
- 跨域脚本的错误处理  

- 使用source map进行错误处理还原  

> 比如我们利用 webpack 打包压缩生成的一份对应脚本的 map 文件进行追踪，在 webpack 中开启 source map 功能：  

```
module.exports = {
    // ...
    devtool: '#source-map',
    // ...
}
```
- 对Promise错误处理  

> 写 Promise 的时候最后写上 catch 函数的习惯。还可以注册对 Promise 全局异常的捕获事件 unhandledrejection：  

```
window.addEventListener("unhandledrejection",  e => {
    e.preventDefault()
    console.log(e.reason)
    return true
})
```
这对于集中管理和错误收集更加友好。  

- 处理网络加载错误  

> 用 script 标签，link 标签进行脚本或者其他资源加载时，由于某种原因（可能是服务器错误，也可能是网络不稳定），导致了脚本请求失败，网络加载错误。为了捕获这些加载异常，我们可以：  

```
<script src="***.js"  onerror="errorHandler(this)"></script>
<link rel="stylesheet" href="***.css" onerror="errorHandler(this)">
```
> 也可以使用 window.addEventListener('error') 方式对加载异常进行处理，注意这时候我们无法使用 window.onerror 进行处理，因为 window.onerror 事件是通过事件冒泡获取 error 信息的，而网络加载错误是不会进行事件冒泡的。  

**window.addEventListener 不同于 window.onerror，它通过事件捕获获取 error 信息，从而可以对网络资源的加载异常进行处理：**   

```
window.addEventListener('error', error => {
    console.log(error)
}, true)
```
普通错误的 error 对象中会有一个 error.message 属性，表示错误信息，而资源加载错误对应的 error 对象却没有  

```
window.addEventListener('error', error => {
    if (!error.message) {
        // 网络资源加载错误
        console.log(error)
    }
}, true)
```
- 页面崩溃收集和处理  

> 可以监听 window 对象的 load 和 beforeunload 事件，并结合 sessionStorage 对网页崩溃实施监控：  

```
window.addEventListener('load', () => {
    sessionStorage.setItem('good_exit', 'pending')
})

window.addEventListener('beforeunload', () => {
    sessionStorage.setItem('good_exit', 'true')
})

if(sessionStorage.getItem('good_exit') &&
    sessionStorage.getItem('good_exit') !== 'true') {
    // 捕获到页面崩溃
}
```

> 在网页 load 事件的回调里：利用 sessionStorage 记录 good_exit 值为 pending；接下来，在页面无异常退出前，即 beforeunload 事件回调中，修改 sessionStorage 记录的 good_exit 值为 true。因此，如果页面没有崩溃的话，good_exit 值都会在离开前设置为 true，否则就可以通过 sessionStorage.getItem('good_exit') && sessionStorage.getItem('good_exit') !== 'true' 判断出页面崩溃，并进行处理。  

- 框架的错误处理  

> Vue 中，提供了 Vue.config.errorHandler 来处理捕获到的错误，如果开发者没有配置 Vue.config.errorHandler，那么捕获到的错误会以 console.error 的方式输出。因此可以劫持 console.error，捕获框架中的错误并做出处理：  

```
const nativeConsoleError = window.console.error
window.console.error = (...args) => nativeConsoleError.apply(this, [`I got ${args}`])
```